//
//  MVPFitObjects.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class MVPFitObjects: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _objectName: String?
    var _objectType: String?
    var _createdBy: String?
    var _createdDate: String?
    var _objectApp: String?
    var _objectInfo: [String: Any]?
    
    class func dynamoDBTableName() -> String {

        return "addysfitnessapp-mobilehub-805122985-MVPFitObjects"
    }
    
    class func hashKeyAttribute() -> String {

        return "_objectName"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_objectType"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_objectName" : "objectName",
               "_objectType" : "objectType",
               "_createdBy" : "createdBy",
               "_createdDate" : "createdDate",
               "_objectApp" : "objectApp",
               "_objectInfo" : "objectInfo",
        ]
    }
}
