//
//  UserAccess.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class UserAccess: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _identityId: String?
    var _admin: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "addysfitnessapp-mobilehub-805122985-UserAccess"
    }
    
    class func hashKeyAttribute() -> String {

        return "_identityId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_identityId" : "identityId",
               "_admin" : "admin",
        ]
    }
}
