//
//  Workouts.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Workouts: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _videoType: String?
    var _pathUrl: String?
    var _tags: String?
    var _videoLength: String?
    var _videoName: String?
    
    class func dynamoDBTableName() -> String {

        return "addysfitnessapp-mobilehub-805122985-Workouts"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_videoType"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_videoType" : "videoType",
               "_pathUrl" : "pathUrl",
               "_tags" : "tags",
               "_videoLength" : "videoLength",
               "_videoName" : "videoName",
        ]
    }
}
