//
//  Workouts.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class Workouts: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _workoutName: String?
    var _createdBy: String?
    var _createdDate: String?
    var _videoDescription: String?
    var _videoLength: String?
    var _workoutType: String?
    
    class func dynamoDBTableName() -> String {

        return "addysfitnessapp-mobilehub-805122985-Workouts"
    }
    
    class func hashKeyAttribute() -> String {

        return "_workoutName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_workoutName" : "WorkoutName",
               "_createdBy" : "CreatedBy",
               "_createdDate" : "CreatedDate",
               "_videoDescription" : "VideoDescription",
               "_videoLength" : "VideoLength",
               "_workoutType" : "WorkoutType",
        ]
    }
}
